backend/blogs/urls.py
from django.urls import include

from common.conf import path
from blogs.views import posts, archive, stories


app_name = 'blogs'


post_urls = [
    path('', posts.PostView.as_view(), 'post'),
    path('edit/', posts.EditPostView.as_view(), 'edit_post'),
    path('like/', posts.LikePostView.as_view(), 'add_like'),
    path('save/', posts.SavePostView.as_view(), 'save_post'),
    path('unlike/', posts.UnlikePostView.as_view(), 'remove_like'),
    path('unsave/', posts.UnsavePostView.as_view(), 'unsave_post'),
    path('delete/', posts.DeletePostView.as_view(), 'delete_post'),
    path('likes/', posts.PostLikesView.as_view(), 'post_likes'),
    path('archive/', archive.ArchivePostView.as_view(), 'archive_post'),
    path('comment/', posts.CommentOnView.as_view(), 'add_comment'),
    path('delete-comment/<int:comment_id>/', posts.DeleteCommentView.as_view(), 'delete_comment'),
    path('add-uninteresting/', posts.AddUninterestingPostView.as_view(), 'add_uninteresting'),
    path('remove-uninteresting/', posts.RemoveUninterestingPostView.as_view(), 'remove_uninteresting'),
]


posts_urls = [
    path('<int:post_id>/', include(post_urls)),
    path('create/', posts.CreatePostView.as_view(), 'create_post'),
    path('tags/<slug:tag_slug>/posts/', posts.TagPostsView.as_view(), 'tag_posts'),
]


archive_urls = [
    path('stories/', archive.ArchivedStoriesView.as_view(), 'archived_stories'),
    path('posts/', archive.ArchivedPostsView.as_view(), 'archived_posts'),
    path('posts/<int:post_id>/', archive.ArchivedPostView.as_view(), 'archived_post'),
    path('posts/<int:post_id>/restore/', archive.RestorePostView.as_view(), 'restore_post'),
]


stories_urls = [
    path('create-story/', stories.CreateStoryView.as_view(), 'create_story'),
    path('delete-story/<int:story_id>/', stories.DeleteStoryView.as_view(), 'delete_story'),
]


urlpatterns = [
    path('', posts.FeedView.as_view(), 'feed'),
    path('explore/', posts.ExploreView.as_view(), 'explore'),
    path('uninteresting-posts/', posts.UninterestingPostsView.as_view(), 'uninteresting_posts'),
    path('posts/', include(posts_urls)),
    path('stories/', include(stories_urls)),
    path('archive/', include(archive_urls)),
]

backend/copygram/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from rest_framework.routers import DefaultRouter
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from two_factor.urls import urlpatterns as tf_urls

from users.api import views as users_api
from blogs.api import views as blogs_api
from chats.api import views as chats_api


r = DefaultRouter()
r.register(r'tags', blogs_api.TagViewSet, 'tag')
r.register(r'users', users_api.UserViewSet, 'user')
r.register(r'referrals', users_api.ReferralViewSet, 'referral')
r.register(r'posts', blogs_api.PostViewSet, 'post')
r.register(r'stories', blogs_api.StoryViewSet, 'story')
r.register(r'uninteresting', blogs_api.UninterestingPostViewSet, 'uninteresting')
r.register(r'groups', chats_api.GroupChatViewSet, 'group')
r.register(r'chats', chats_api.PrivateChatViewSet, 'chat')
r.register(r'actions', users_api.ActionViewSet, 'action')
r.register(r'archive', blogs_api.ArchiveViewSet, 'archive')
r.register(r'activity', users_api.ActivityViewSet, 'activity')
r.register(r'blocked', users_api.BlockedUsersViewSet, 'blocked')
r.register(r'saved-posts', users_api.SavedPostsViewSet, 'saved-post')
r.register(r'recommendations', users_api.RecommendationViewSet, 'recommendation')
r.register(r'activities', users_api.UserActivityViewSet, 'user-activity')


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('rest_framework.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('two-factor/', include(tf_urls)),

    path('api/', include(r.urls)),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path(
        route='api/docs/',
        view=SpectacularSwaggerView.as_view(url_name='schema'),
        name='swagger-ui',
    ),
    path('api/social-auth/', include('drf_social_oauth2.urls', namespace='drf')),
    path('', include('users.urls', namespace='users')),
    path('', include('chats.urls', namespace='chats')),
    path('', include('blogs.urls', namespace='blogs')),
]


if settings.DEBUG:
    urlpatterns += static(
        prefix=settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

backend/users/urls.py
from django.urls import reverse_lazy, include
from django.contrib.auth.views import (
    LogoutView,
    PasswordChangeView,
    PasswordResetDoneView,
    PasswordResetConfirmView
)
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from two_factor.views.core import LoginView

from common.conf import path
from users.api import views
from users.views import accounts, actions, followers, auth


app_name = 'users'


user_urls = [
    path('', accounts.ProfileView.as_view(), 'profile'),
    path('followers/', followers.FollowersView.as_view(), 'followers'),
    path('following/', followers.FollowingView.as_view(), 'following'),
    path('follow/', followers.FollowUserView.as_view(), 'follow'),
    path('unfollow/', followers.UnfollowUserView.as_view(), 'unfollow'),
    path('block/', accounts.BlockUserView.as_view(), 'block'),
    path('unblock/', accounts.UnblockUserView.as_view(), 'unblock'),
    path('report/', actions.CreateReportView.as_view(), 'create_report'),
]


password_urls = [
    path('password-reset/',auth.PasswordResetView.as_view(), 'password_reset'),
    path('password-user-confirm/', auth.PasswordUserConfirmView.as_view(),'password_user_confirm'),
    path(
        route='password-reset/done/',
        view=PasswordResetDoneView.as_view(
            template_name="info_page.html"
        ),
        name='password_reset_done',
    ),
    path(
        route='password-reset/<uidb64>/<token>/',
        view=PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url=reverse_lazy('users:login'),
        ),
        name='password_reset_confirm',
    ),
    path(
        route='change-password/',
        view=PasswordChangeView.as_view(
            success_url=reverse_lazy('blogs:feed'),
            template_name='users/change_password.html',
        ),
        name='change_password',
    ),
]


actions_urls = [
    path('actions/', actions.ActionsView.as_view(), 'actions'),
    path('clear-actions/', actions.ClearActionsView.as_view(), 'clear_actions'),
    path('delete-action/<int:action_id>/', actions.DeleteActionView.as_view(), 'delete_action'),
]


auth_urls = [
    path('login/', LoginView.as_view(template_name="users/login.html"), 'login'),
    path('logout/', LogoutView.as_view(), 'logout'),
    path('register/', auth.RegisterView.as_view(), 'register'),
    path('register-confirm/<uidb64>/<token>/', auth.RegisterConfirmView.as_view(), 'register_confirm'),
]


api_urls = [
    path('api/settings/', views.SettingsAPIView.as_view()),
    path('api/vip-status/', views.VipAPIView.as_view()),
    path('api/token/', TokenObtainPairView.as_view(), 'token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), 'token_refresh'),
    path('api/register-confirm/<uidb64>/<token>/',views.RegisterConfirmAPIView.as_view()),
    path('api/accept-follower/<slug:user_slug>/', views.AcceptFollowerAPIView.as_view()),
    path('api/reject-follower/<slug:user_slug>/', views.RejectFollowerAPIView.as_view()),
    path('api/password-change/', views.PasswordChangeAPIView.as_view()),
    path('api/password-reset/', views.PasswordResetAPIView.as_view()),
    path('api/password-reset-confirm/<uidb64>/<token>/', views.PasswordResetConfirmAPIView.as_view()),
]


urlpatterns = [
    path('activity/', actions.ActivityView.as_view(), 'activity'),
    path('saved-posts/', actions.SavedPostsView.as_view(), 'saved_posts'),
    path('blocked/', accounts.BlockedView.as_view(), 'blocked'),
    path('search/', actions.SearchView.as_view(), 'search'),
    path('users/edit/', accounts.EditProfileView.as_view(), 'edit_profile'),
    path('users/<slug:user_slug>/', include(user_urls)),
    path('settings/', accounts.EditSettingsView.as_view(), 'edit_settings'),
    path('accept-follower/<slug:user_slug>/', followers.AcceptFollowerView.as_view(), 'accept_follower'),
    path('reject-follower/<slug:user_slug>/', followers.RejectFollowerView.as_view(), 'reject_follower'),
    path('delete-account/', accounts.DeleteProfileView.as_view(), 'delete_account'),
    path('two_fa/', auth.SetupTwoFaView.as_view(), 'enable_fa'),
    path('disable-two-fa/', auth.DisableTwoFaView.as_view(), 'disable_fa'), 
] + password_urls + actions_urls + auth_urls + api_urls

backend/chats/models.py
from django.db import models
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import (
    GenericForeignKey,
    GenericRelation,
)

from common.models import BaseModel
from chats.managers import ChatManager


class PrivateChat(models.Model):
    users = models.ManyToManyField('users.User', related_name='private_chats')
    messages = GenericRelation('chats.Message', related_query_name='private_chat')

    objects = ChatManager()


class GroupChat(BaseModel):
    owner = models.ForeignKey(
        to='users.User',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='group_owner',
    )
    image = models.ImageField(upload_to='rooms/%Y/%m/%d/', blank=True)
    name = models.CharField(max_length=50)
    users = models.ManyToManyField('users.User', related_name='group_chats')
    messages = GenericRelation('chats.Message', related_query_name='group_chat')

    objects = ChatManager()

    def __str__(self):
        return self.name


class Message(BaseModel):
    user = models.ForeignKey(
        to='users.User',
        on_delete=models.CASCADE,
        related_name='messages',
    )
    content = models.TextField(blank=True)
    content_type = models.ForeignKey(
        to=ContentType,
        on_delete=models.CASCADE,
        limit_choices_to={'model__in': ('groupchat', 'privatechat')}
    )
    object_id = models.PositiveIntegerField()
    chat = GenericForeignKey('content_type', 'object_id')


class MessageImage(models.Model):
    message = models.ForeignKey(
        to='chats.Message',
        on_delete=models.CASCADE,
        related_name='files'
    )
    file = models.FileField(upload_to='messages/%Y/%m/%d/', blank=True)

backend/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from users.models import Report, UserPrivacy, User


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            'username',
            'avatar',
            'email',
            'password1',
            'password2',
        ]


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            'avatar',
            'bio',
            'gender',
        ]


class CustomPasswordResetForm(forms.Form):
    email = forms.EmailField(
        label="Email",
        max_length=254,
        widget=forms.EmailInput(attrs={"autocomplete": "email"}),
    )

    def clean_email(self):
        email = self.cleaned_data['email']
        if not User.objects.filter(email=email).exists():
            raise forms.ValidationError('User is not found')
        return email


class ReportForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = ['reason']


class UserPrivacyForm(forms.ModelForm):
    class Meta:
        model = UserPrivacy
        exclude = ['user']

backend/users/views/accounts.py
from django.http import Http404
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.views import View
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView, DeleteView
from django.views.generic.list import ListView
from two_factor.utils import default_device

from common.utils import redis_client
from users.forms import UserEditForm, UserPrivacyForm
from users.models import User, UserPrivacy
from users.utils import block_user, get_user_posts, get_users, unblock_user
from users.recommendations import Recommender
from blogs.models import Story


class ProfileView(DetailView):
    model = User
    template_name = 'users/profile.html'
    context_object_name = 'user'
    slug_url_kwarg = 'user_slug'

    def get_queryset(self):
        user = self.request.user
        queryset = get_users(user).select_related('privacy')
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.object
        current_user = self.request.user

        context['posts'] = get_user_posts(user_id=user.id)
        context['stories'] = (
            Story.objects.filter(owner=user).
            exclude(archived=True).
            select_related('owner')
        )

        # handle follow requests
        key = f'user:{user.username}:requests'
        user_requests = redis_client.smembers(key)
        if str(current_user.username) in user_requests:
            context['request_to_follow'] = True
        else:
            context['request_to_follow'] = False

        # recommendations for user
        recommendations = Recommender(user).get_follows_ids()
        context['recommendations'] = User.objects.filter(id__in=recommendations)
        return context


class DeleteProfileView(DeleteView):
    model = User
    success_url = reverse_lazy('users:login')

    def get_object(self, queryset=None):
        return self.request.user


class EditProfileView(UpdateView):
    model = User
    form_class = UserEditForm
    template_name = 'users/edit_profile.html'

    def get_object(self, queryset=None):
        return self.request.user

    def get_success_url(self):
        return self.request.user.get_absolute_url()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_enable'] = True if default_device(self.object) else False
        return context


class EditSettingsView(UpdateView):
    model = UserPrivacy
    form_class = UserPrivacyForm
    template_name = 'users/settings.html'

    def get_object(self, queryset=None):
        return UserPrivacy.objects.get(user_id=self.request.user.id)

    def get_success_url(self):
        return self.request.user.get_absolute_url()


class BlockedView(ListView):
    template_name = 'users/blocked.html'
    context_object_name = 'users'

    def get_queryset(self):
        user = self.request.user
        queryset = User.objects.blocked(user=user)
        return queryset


class BlockUserView(View):

    def post(self, request, user_slug):
        user = request.user
        to_user = User.objects.get(slug=user_slug)
        response = block_user(user, to_user)
        if response == 'Already blocked':
            return Http404('User is already blocked')
        return redirect('users:profile', user.slug)


class UnblockUserView(View):

    def post(self, request, user_slug):
        user = request.user
        to_user = User.objects.get(slug=user_slug)
        response = unblock_user(user, to_user)
        if response == 'Not blocked':
            return Http404('User is not blocked')
        return redirect('users:profile', user.slug)

backend/users/views/followers.py
from django.http import JsonResponse
from django.shortcuts import redirect
from django.views import View

from users.models import User
from users.mixins import FollowersMixin
from users.utils import follow_user, process_follower_request, unfollow_user


class FollowersView(FollowersMixin):
    extra_context = {'title': 'followers'}

    def get_queryset(self):
        qs = super().get_queryset()
        queryset = qs.filter(following__to_user__slug=self.user_slug)
        return queryset


class FollowingView(FollowersMixin):
    extra_context = {'title': 'following'}

    def get_queryset(self):
        qs = super().get_queryset()
        queryset = qs.filter(followers__from_user__slug=self.user_slug)
        return queryset


class FollowUserView(View):

    def post(self, request, user_slug):
        from_user = request.user
        to_user = User.objects.get(slug=user_slug)
        response = follow_user(from_user, to_user)
        return JsonResponse({'status': response})


class UnfollowUserView(View):

    def delete(self, request, user_slug):
        from_user = request.user
        to_user = User.objects.get(slug=user_slug)
        response = unfollow_user(from_user, to_user)
        return JsonResponse({'status': response})


class AcceptFollowerView(View):

    def post(self, request, user_slug):
        response = process_follower_request(user_slug, request.user, 'accept')
        if response == 'Accepted':
            return redirect('users:actions')
        return JsonResponse({'status': response})


class RejectFollowerView(View):

    def post(self, request, user_slug):
        response = process_follower_request(user_slug, request.user, 'reject')
        if response == 'Rejected':
            return redirect('users:actions')
        return JsonResponse({'status': response})

backend/users/templates/users/actions.html
{% extends "base.html" %}
{% load static %}

{% block title %}Actions{% endblock title %}

{% block content %}
	{% if actions %}
		<form method="post" action="{% url 'users:clear_actions' %}">
			{% csrf_token %}
			<button class="btn btn-success mb-2">Clear</button>
		</form>
		{% for action in actions %}
			<div class="card w-75 mb-2">
				<div class="card-body bg-dark rounded">
					<h5 class="card-title text-light">{{ action.owner }}</h5>
					<p class="card-text text-light">{{ action.act }}</p>
					{% if action.file %}
						<img src="{{ action.file.url }}"
							alt="Generic placeholder image" class="img-fluid"
							style="width: 100px; border-radius: 10px;">
					{% endif %}
					<p class="card-text"><small class="text-muted">{{ action.created }}</small></p>
					{% if action.act|slice:":5" == 'wants' %}
						<form method="post" 
								action="{% url 'users:accept_follower' action.owner.slug %}">
								{% csrf_token %}
								<button class="btn btn-success mb-2">Accept</button>
						</form>
						<form method="post" 
								action="{% url 'users:reject_follower' action.owner.slug %}">
								{% csrf_token %}
								<button class="btn btn-success mb-2">Reject</button>
						</form>
					{% else %}
						<button id="action-{{ action.id }}" 
						class="btn btn-success delete-action">Delete</button>
					{% endif %}
				</div>
			</div>
	{% endfor %}
	{% else %}
	  <div class="alert alert-info" role="alert">
			You don't have any actions.
		</div>
	{% endif %}
	
{% endblock content %}

{% block jscontent %}
	<script src="//cdn.jsdelivr.net/npm/js-cookie@3.0.1/dist/js.cookie.min.js"></script>
	<script>
		const url = "{% url 'users:delete_action' 0 %}"
	</script>
	<script src="{% static 'users/js/actions.js' %}"></script>
{% endblock jscontent %}

backend/users/templates/users/disable_fa.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{% block content %}
	<h1>{% block title %}{% trans "Disable Two-factor Authentication" %}{% endblock %}</h1>
	<p>{% blocktrans trimmed %}You are about to disable two-factor authentication. This
		weakens your account security, are you sure?{% endblocktrans %}
	</p>
	<form method="post">
		{% csrf_token %}
		<table>{{ form.as_table }}</table>
		<button class="btn btn-danger"
			type="submit">
			{% trans "Disable" %}
		</button>
	</form>
{% endblock %}

backend/users/templates/users/edit_profile.html
{% extends "default_form.html" %}
{% load django_bootstrap5 %}

{% block title %}Edit{% endblock title %}

{% block text_form %}
	<button class="btn btn-success">Save</button>
	{% if perms.users.social_auth %}
		<a class="btn btn-success" href="{% url 'users:change_password' %}">Change password</a>
	{% endif %}
	{% if is_enable %}
		<a class="btn btn-success" href="{% url 'users:disable_fa' %}">Disable 2fa</a>
	{% else %}
		<a class="btn btn-success" href="{% url 'users:enable_fa' %}">Enable 2fa</a>
	{% endif %}
{% endblock text_form %}

backend/users/templates/users/password_reset.html
{% extends "default_form.html" %}
{% load django_bootstrap5 %}

{% block title %}Reset password{% endblock title %}

{% block text_form %}
	<button class="btn btn-success">Reset</button>
{% endblock text_form %}

backend/users/templates/users/profile.html
{% extends "base.html" %}
{% load static %}
{% load django_bootstrap5 %}

{% block title %}Profile{% endblock title %}

{% block content %}
	<div class="row d-flex align-items-center h-100">
		<div class="col col-md-9 col-lg-7 col-xl-5">
			<div class="card bg-dark" style="border-radius: 15px;">
				<div class="card-body p-4">
					<div class="d-flex text-black">
						<div class="flex-shrink-0">
							{% if user.avatar %}
								<img src="{{ user.avatar.url }}"
									alt="Generic placeholder image" class="img-fluid"
									style="width: 100px; border-radius: 20px;">
							{% else %}
								<img src="{% static 'users/img/user.png' %}"
									alt="Generic placeholder image" class="img-fluid"
									style="width: 100px; border-radius: 20px;">
							{% endif %}
						</div>
						<div class="flex-grow-1 ms-3">
							<h5 class="mb-1 text-light">{{ user.username }}
								{% if user.privacy.online_status == 'followers' and user.is_followed %}
									<span class="badge rounded-pill bg-success">
										{% if user.is_online %}
											Online
										{% else %}
											Offline
										{% endif %}
									</span>
								{% elif user.privacy.online_status == 'everyone' %}
									<span class="badge rounded-pill bg-success">
										{% if user.is_online %}
											Online
										{% else %}
											Offline
										{% endif %}
									</span>
								{% endif %}
							</h5>
							<p class="mb-2 pb-1 text-light">{{ user.first_name }} {{ user.last_name }}</p>
							<p class="mb-2 pb-1 text-muted">{{ user.bio }}</p>
							<div class="d-flex pt-1">
								{% if not user.is_followed and user.privacy.private_account and user != request.user %}
									<p class="mb-2 pb-1 text-light me-2">
										<a href="#">
											<span id="followers">{{ user.followers_count }} </span>
											followers
										</a>
									</p>
									<p class="mb-2 pb-1 text-light">
										<a href="#">{{ user.following_count }} following</a>
									</p>
								{% else %}
									<p class="mb-2 pb-1 text-light me-2">
										<a href="{% url 'users:followers' user.slug %}">
											<span id="followers">{{ user.followers_count }} </span>
											followers
										</a>
									</p>
									<p class="mb-2 pb-1 text-light">
										<a href="{% url 'users:following' user.slug %}">
											{{ user.following_count }} following</a>
									</p>
								{% endif %}
							</div>
							<div class="d-flex pt-1">
								{% if user == request.user %}
									<a class="btn btn-success me-1 flex-grow-1" 
										href="{% url 'users:edit_profile'%}" 
										role="button">Edit</a>
									<a class="btn btn-success me-1 flex-grow-1" 
										href="{% url 'blogs:create_post' %}" 
										role="button">Add post</a>
									<a class="btn btn-success me-1 flex-grow-1" 
										href="{% url 'blogs:create_story' %}" 
										role="button">Add story</a>
									<form action="{% url 'users:delete_account' %}" method="post">
										{% csrf_token %}
										<button class="btn btn-success">Delete account</button>
									</form>
								{% else %}
									<button id="follow" type="button" 
										class="btn btn-success me-1 flex-grow-1">
										{% if request_to_follow %}
											Cancel
										{% elif user.is_followed %}
											Unfollow
										{% else %}
											Follow
										{% endif %}
									</button>
									<form action="{% url 'users:block' user.slug %}" method="post">
										{% csrf_token %}
										<button class="btn btn-success me-1 flex-grow-1">Block</button>
									</form>
									<a class="btn btn-success me-1 flex-grow-1" 
										href="{% url 'users:create_report' user.slug %}"
										role="button">
										Report
									</a>
									{% if is_chat %}
										<a class="btn btn-success" 
											href="{% url 'chats:private_chat' is_chat.id %}" 
											role="button">
											Message
										</a>
									{% else %}
										<form action="{% url 'chats:create_private' user.slug %}" method="post">
											{% csrf_token %}
											<button class="btn btn-success flex-grow-1">Message</button>
										</form>
									{% endif %}
								{% endif %}
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	{% if not user.is_followed and user.privacy.private_account and user != request.user %}
		<p class="display-5">Private account:</p> 
	{% else %}
		<div class="row row-cols-1 row-cols-md-5 g-4 mt-1">
			{% for post in posts %}
				<div class="col">
					<div class="card h-100" style="border-radius: 20px; overflow: hidden;">
						<a href="{{ post.get_absolute_url }}">
							{% if post.file|slice:"-4:" == ".mp4" %}
								<video height="225">
									<source src="{{ post.file }}" type="video/mp4">
								</video>
							{% else %}
								<img class="card-img-top" src="{{ post.file }}" 
									alt="Card image cap" height="225">
							{% endif %}
						</a>
						<div class="card-body bg-dark">
						</div>
					</div>
				</div>
			{% endfor %}
		</div>
		{% if stories %}
			<p class="display-5">Stories:</p>
			<div class="row row-cols-1 row-cols-md-5 g-4">
				{% for story in stories %}
					<div class="col">
						<div class="card h-100" style="border-radius: 20px; overflow: hidden;">
							<div class="card-body bg-dark">
								{% if request.user == user %}
									<form action="{% url 'blogs:delete_story' story.id %}" 
										method="post">
										{% csrf_token %}
										<button class="btn btn-success">Delete</button>
									</form>
								{% endif %}
							</div>
							<img class="card-img-top" src="{{ story.img.url }}" 
								alt="Card image cap" height="225">
						</div>
					</div>
				{% endfor %}
			</div>
		{% endif %}
	{% endif %}
	{% if user == request.user %}
		<p class="pt-3">
			<button class="btn btn-success" type="button" data-bs-toggle="collapse" 
				data-bs-target="#collapseWidthExample" aria-expanded="false" 
				aria-controls="collapseWidthExample">
				Recommendations
			</button>
		</p>
		{% if recommendations %}
			<div class="card-group">
			{% for recommended_user in recommendations %}
				<div style="min-height: 120px;">
					<div class="collapse collapse-horizontal" id="collapseWidthExample">
						<div class="card card-body bg-dark" style="width: 300px;">
							{% if recommended_user.avatar %}
								<img src="{{ recommended_user.avatar.url }}"
									alt="Generic placeholder image" class="img-fluid"
									style="width: 100px; border-radius: 10px;">
							{% else %}
								<img src="{% static 'users/img/user.png' %}"
									alt="Generic placeholder image" class="img-fluid"
									style="width: 100px; border-radius: 20px;">
							{% endif %}
							<a href="{{ recommended_user.get_absolute_url }}">{{ recommended_user.username }}</a>
							<div class="d-flex pt-1">
								<button id="follow-{{ recommended_user.slug }}" type="button" 
									class="btn btn-success me-1 flex-grow-1 follow-recomendation">
									Follow
								</button>
							</div>
						</div>
					</div>
				</div>
			{% endfor %}
			</div>
		{% endif %}
	{% endif %}
{% endblock content %}

{% block jscontent %}
	<script src="//cdn.jsdelivr.net/npm/js-cookie@3.0.1/dist/js.cookie.min.js"></script>
	<script>
		const follow_endpoint = "{% url 'users:follow' user.slug %}"
		const unfollow_endpoint = "{% url 'users:unfollow' user.slug %}"
		const user_ = '{{ user.username }}'
		const users_slug = '{{ user.slug }}'
		const curr_user = '{{ request.user }}'
	</script>
	{% if user == request.user %}
		<script src="{% static 'users/js/recommend.js' %}"></script>
	{% else %}
		<script src="{% static 'users/js/profile.js' %}"></script>
	{% endif %}
{% endblock jscontent %}

backend/users/templates/users/settings.html
{% extends "default_form.html" %}
{% load django_bootstrap5 %}

{% block title %}Settings{% endblock title %}

{% block text_form %}
	<button class="btn btn-success">Save</button>
{% endblock text_form %}