backend/blogs/urls.py
from django.urls import include

from common.conf import path
from blogs.views import posts, archive, stories


app_name = 'blogs'


post_urls = [
    path('', posts.PostView.as_view(), 'post'),
    path('edit/', posts.EditPostView.as_view(), 'edit_post'),
    path('like/', posts.LikePostView.as_view(), 'add_like'),
    path('save/', posts.SavePostView.as_view(), 'save_post'),
    path('unlike/', posts.UnlikePostView.as_view(), 'remove_like'),
    path('unsave/', posts.UnsavePostView.as_view(), 'unsave_post'),
    path('delete/', posts.DeletePostView.as_view(), 'delete_post'),
    path('likes/', posts.PostLikesView.as_view(), 'post_likes'),
    path('archive/', archive.ArchivePostView.as_view(), 'archive_post'),
    path('comment/', posts.CommentOnView.as_view(), 'add_comment'),
    path('delete-comment/<int:comment_id>/', posts.DeleteCommentView.as_view(), 'delete_comment'),
    path('add-uninteresting/', posts.AddUninterestingPostView.as_view(), 'add_uninteresting'),
    path('remove-uninteresting/', posts.RemoveUninterestingPostView.as_view(), 'remove_uninteresting'),
]


posts_urls = [
    path('<int:post_id>/', include(post_urls)),
    path('create/', posts.CreatePostView.as_view(), 'create_post'),
    path('tags/<slug:tag_slug>/posts/', posts.TagPostsView.as_view(), 'tag_posts'),
]


archive_urls = [
    path('stories/', archive.ArchivedStoriesView.as_view(), 'archived_stories'),
    path('posts/', archive.ArchivedPostsView.as_view(), 'archived_posts'),
    path('posts/<int:post_id>/', archive.ArchivedPostView.as_view(), 'archived_post'),
    path('posts/<int:post_id>/restore/', archive.RestorePostView.as_view(), 'restore_post'),
]


stories_urls = [
    path('create-story/', stories.CreateStoryView.as_view(), 'create_story'),
    path('delete-story/<int:story_id>/', stories.DeleteStoryView.as_view(), 'delete_story'),
]


urlpatterns = [
    path('', posts.FeedView.as_view(), 'feed'),
    path('explore/', posts.ExploreView.as_view(), 'explore'),
    path('uninteresting-posts/', posts.UninterestingPostsView.as_view(), 'uninteresting_posts'),
    path('posts/', include(posts_urls)),
    path('stories/', include(stories_urls)),
    path('archive/', include(archive_urls)),
]

backend/copygram/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from rest_framework.routers import DefaultRouter
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from two_factor.urls import urlpatterns as tf_urls

from users.api import views as users_api
from blogs.api import views as blogs_api
from chats.api import views as chats_api


r = DefaultRouter()
r.register(r'tags', blogs_api.TagViewSet, 'tag')
r.register(r'users', users_api.UserViewSet, 'user')
r.register(r'referrals', users_api.ReferralViewSet, 'referral')
r.register(r'posts', blogs_api.PostViewSet, 'post')
r.register(r'stories', blogs_api.StoryViewSet, 'story')
r.register(r'uninteresting', blogs_api.UninterestingPostViewSet, 'uninteresting')
r.register(r'groups', chats_api.GroupChatViewSet, 'group')
r.register(r'chats', chats_api.PrivateChatViewSet, 'chat')
r.register(r'actions', users_api.ActionViewSet, 'action')
r.register(r'archive', blogs_api.ArchiveViewSet, 'archive')
r.register(r'activity', users_api.ActivityViewSet, 'activity')
r.register(r'blocked', users_api.BlockedUsersViewSet, 'blocked')
r.register(r'saved-posts', users_api.SavedPostsViewSet, 'saved-post')
r.register(r'recommendations', users_api.RecommendationViewSet, 'recommendation')
r.register(r'activities', users_api.UserActivityViewSet, 'user-activity')


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('rest_framework.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('two-factor/', include(tf_urls)),

    path('api/', include(r.urls)),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path(
        route='api/docs/',
        view=SpectacularSwaggerView.as_view(url_name='schema'),
        name='swagger-ui',
    ),
    path('api/social-auth/', include('drf_social_oauth2.urls', namespace='drf')),
    path('', include('users.urls', namespace='users')),
    path('', include('chats.urls', namespace='chats')),
    path('', include('blogs.urls', namespace='blogs')),
]


if settings.DEBUG:
    urlpatterns += static(
        prefix=settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

backend/blogs/models.py
from io import BytesIO
from uuid import uuid4
from PIL import Image, UnidentifiedImageError
from django.utils import timezone
from django.db import models, transaction
from django.urls import reverse
from django.contrib.contenttypes.fields import GenericRelation
from django.core.files.base import ContentFile
from tree_queries.models import TreeNode
from taggit.managers import TaggableManager

from blogs.managers import CommentQuerySet, PostManager
from common.models import BaseModel


class BaseMedia(BaseModel):
    class Meta:
        abstract = True

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.old_archived = self.archived


class Post(BaseMedia):
    owner = models.ForeignKey(
        to='users.User',
        on_delete=models.CASCADE,
        related_name='posts',
    )
    description = models.TextField(blank=True)
    likes = models.ManyToManyField('users.User', related_name='likes', blank=True)
    saved = models.ManyToManyField('users.User', related_name='saved', blank=True)
    is_comment = models.BooleanField(default=True)
    actions = GenericRelation('users.Action', related_query_name='post')
    archived = models.BooleanField(default=False)
    tags = TaggableManager(blank=True)

    objects = PostManager()

    @transaction.atomic
    def save(self, *args, **kwargs):
        if not self.pk:
            self.owner.last_activity = timezone.now()
            self.owner.save()
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blogs:post', kwargs={'post_id': self.pk})

    def get_files(self):
        return self.files.select_related('post')

    def get_tags(self):
        return self.tags.all()


# Post -> PostMedia
class PostMedia(models.Model):
    post = models.ForeignKey(
        to='blogs.Post',
        related_name='files',
        on_delete=models.CASCADE,
    )
    file = models.FileField(upload_to='posts/%Y/%m/%d/')

    class Meta:
        verbose_name_plural = 'Posts media'

    def process_image(self):
        if not self.pk:
            try:
                img = Image.open(self.file)
            except UnidentifiedImageError:
                pass
            else:
                if img.mode in ("RGBA", "LA", "P"):
                    img = img.convert("RGB")
                size = (350, 225)
                img = img.resize(size, Image.LANCZOS)

                temp_img = BytesIO()
                img.save(temp_img, format='JPEG', optimize=True, quality=100)
                temp_img.seek(0)

                img_name = f"{uuid4()}.jpg"
                self.file.save(
                    name=img_name,
                    content=ContentFile(temp_img.read()),
                    save=False,
                )

    @classmethod
    def bulk_create_with_processing(cls, objs):
        # Process images for each object
        for obj in objs:
            obj.process_image()

        # Bulk create the objects
        cls.objects.bulk_create(objs)

    def save(self, *args, **kwargs):
        self.process_image()
        super().save(*args, **kwargs)


# Post -> Comment
class Comment(TreeNode, BaseModel):
    owner = models.ForeignKey(
        to='users.User',
        related_name='comments',
        on_delete=models.CASCADE,
    )
    post = models.ForeignKey(
        to='blogs.Post',
        on_delete=models.CASCADE,
        related_name='comments',
    )
    parent = models.ForeignKey(
        to='self',
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name='replies',
    )
    likes = models.ManyToManyField(
        to='users.User',
        related_name='comment_likes',
        blank=True,
    )
    text = models.CharField(max_length=255)

    objects = CommentQuerySet.as_manager()


class UninterestingPost(models.Model):
    user = models.ForeignKey(
        to='users.User',
        on_delete=models.CASCADE,
        related_name='uninteresting_posts'
    )
    post = models.ForeignKey(
        to='blogs.Post',
        on_delete=models.CASCADE,
        related_name='uninteresting_by'
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'post'],
                name='unique_uninteresting_post',
            ),
        ]

    def __str__(self):
        return f'{self.user} not interested in {self.post}'


class Story(BaseMedia):
    owner = models.ForeignKey(
        to='users.User',
        on_delete=models.CASCADE,
        related_name='stories',
    )
    img = models.ImageField(upload_to='stories/%Y/%m/%d/')
    archived = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = 'Stories'

    @transaction.atomic
    def save(self, *args, **kwargs):
        return super().save(*args, **kwargs)

backend/chats/models.py
from django.db import models
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import (
    GenericForeignKey,
    GenericRelation,
)

from common.models import BaseModel
from chats.managers import ChatManager


class PrivateChat(models.Model):
    users = models.ManyToManyField('users.User', related_name='private_chats')
    messages = GenericRelation('chats.Message', related_query_name='private_chat')

    objects = ChatManager()


class GroupChat(BaseModel):
    owner = models.ForeignKey(
        to='users.User',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='group_owner',
    )
    image = models.ImageField(upload_to='rooms/%Y/%m/%d/', blank=True)
    name = models.CharField(max_length=50)
    users = models.ManyToManyField('users.User', related_name='group_chats')
    messages = GenericRelation('chats.Message', related_query_name='group_chat')

    objects = ChatManager()

    def __str__(self):
        return self.name


class Message(BaseModel):
    user = models.ForeignKey(
        to='users.User',
        on_delete=models.CASCADE,
        related_name='messages',
    )
    content = models.TextField(blank=True)
    content_type = models.ForeignKey(
        to=ContentType,
        on_delete=models.CASCADE,
        limit_choices_to={'model__in': ('groupchat', 'privatechat')}
    )
    object_id = models.PositiveIntegerField()
    chat = GenericForeignKey('content_type', 'object_id')


class MessageImage(models.Model):
    message = models.ForeignKey(
        to='chats.Message',
        on_delete=models.CASCADE,
        related_name='files'
    )
    file = models.FileField(upload_to='messages/%Y/%m/%d/', blank=True)

backend/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" type="image/png" 
      href="{% static 'img/favicon.png' %}">
    <title>{% block title %}{% endblock title %}</title>
    {% load django_bootstrap5 %} {% bootstrap_css %} {% bootstrap_javascript %}
    <style>
      a {
				color: white;
				text-decoration: none;
      }
    </style>
  </head>
  <body>
    <nav class="navbar navbar-dark bg-dark navbar-expand-lg 
      navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'blogs:feed' %}">COPYGRAM</a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blogs:explore' %}">Explore</a>
            </li>
            {% if user.is_authenticated %}
							{% if user.is_superuser and user.is_staff %}
								<li class="nav-item">
									<a class="nav-link" href="{% url 'admin:index' %}">Admin page</a>
								</li>
							{% endif %}
            	{% with user=request.user %}
								<li class="nav-item">
									<a class="nav-link" href="{{ user.get_absolute_url }}">Profile</a>
								</li>
								<li class="nav-item dropdown">
									<a class="nav-link dropdown-toggle" href="#" 
										role="button" data-bs-toggle="dropdown" 
										aria-expanded="false">
									{{ user.username }}
									</a>
									<ul class="dropdown-menu">
										<li>
											<form action="{% url 'users:logout' %}" method="post">
												{% csrf_token %}
												<button class="dropdown-item">
													Logout
												</button>
											</form>
										</li>
										<li>
											<a class="dropdown-item" 
												href="{% url 'users:blocked' %}">Blocked</a>
										</li>
										<li>
											<a class="dropdown-item" 
												href="{% url 'blogs:archived_posts' %}">Archived posts</a>
										</li>
										<li>
											<a class="dropdown-item" 
												href="{% url 'blogs:archived_stories' %}">Archived stories</a>
										</li>
										<li>
											<a class="dropdown-item" 
												href="{% url 'blogs:uninteresting_posts' %}">Uninteresting posts</a>
										</li>
										<li>
											<a class="dropdown-item" 
												href="{% url 'users:activity' %}">Activity</a>
										</li>
										<li>
											<a class="dropdown-item" 
												href="{% url 'users:saved_posts' %}">Saved</a>
										</li>
										<li>
											<a class="dropdown-item" 
												href="{% url 'users:edit_settings' %}">Settings</a>
										</li>
									</ul>
								</li>
							{% endwith %}
							<li class="nav-item">
								<a class="nav-link" href="{% url 'users:actions' %}">Actions
								{% if unread_actions %}
									<span id="unread-messages">{{ unread_actions }}</span>
								{% endif %}
								</a>
							</li>
							<li class="nav-item">
								<a class="nav-link" href="{% url 'chats:private_chats' %}">Chats
								{% if unread_chat_messages %}
									<span id="unread-messages">{{ unread_chat_messages }}</span>
								{% endif %}
								</a>
							</li>
							<li class="nav-item">
								<a class="nav-link" href="{% url 'chats:groups' %}">Groups
								{% if unread_group_messages %}
									<span id="unread-messages">{{ unread_group_messages }}</span>
								{% endif %}
								</a>
							</li>
            {% else %}
							<li class="nav-item">
								<a class="nav-link" href="{% url 'users:login' %}">Login</a>
							</li>
							<li class="nav-item">
								<a class="nav-link" href="{% url 'users:register' %}">Register</a>
							</li>
            {% endif %}
          </ul>
        </div>
        <form action="{% url 'users:search' %}" class="d-flex">
          <input type="search" id="search-form" class="form-control me-2" name="q"/>
          <button class="btn btn-success">Search</button>
        </form>
      </div>
    </nav>
    <div class="container-fluid mt-3 ms-1 mb-3">
      {% block content %}{% endblock content %}
    </div>
    <script>
      const user = '{{ request.user.username }}'
    </script>
    {% block jscontent %}{% endblock jscontent %}
  </body>
</html>

backend/templates/default_form.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block content %}
  <form method="post" enctype="multipart/form-data"> 
    {% csrf_token %}
    {% bootstrap_form form %}
    {% block text_form %}{% endblock text_form %}
  </form>
{% endblock content %}

backend/templates/info_page.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block content %}
  {% for message in messages %}
    <div class="alert alert-info" role="alert">{{ message }}</div>
  {% endfor %}
{% endblock content %}